module.exports = [
  { name: "U.S Dollars", symbol: "$", value: "USD" },
  { name: "Euro", symbol: "€", value: "EUR" },
  { name: "British Pound", symbol: "£", value: "GBP" },
  { name: "Japanese Yen", symbol: "¥", value: "JPY" },
  { name: "Australian Dollar", symbol: "A$", value: "AUD" },
  { name: "Canadian Dollar", symbol: "C$", value: "CAD" },
  { name: "Swiss Franc", symbol: "CHF", value: "CHF" },
  { name: "Chinese Yuan", symbol: "¥", value: "CNY" },
  { name: "Swedish Krona", symbol: "kr", value: "SEK" },
  { name: "New Zealand Dollar", symbol: "NZ$", value: "NZD" },
  { name: "Mexican Peso", symbol: "Mex$", value: "MXN" },
  { name: "Singapore Dollar", symbol: "S$", value: "SGD" },
  { name: "Hong Kong Dollar", symbol: "HK$", value: "HKD" },
  { name: "Norwegian Krone", symbol: "kr", value: "NOK" },
  { name: "South Korean Won", symbol: "₩", value: "KRW" },
  { name: "Turkish Lira", symbol: "₺", value: "TRY" },
  { name: "Russian Ruble", symbol: "₽", value: "RUB" },
  { name: "Indian Rupee", symbol: "₹", value: "INR" },
  { name: "Brazilian Real", symbol: "R$", value: "BRL" },
  { name: "South African Rand", symbol: "R", value: "ZAR" },
  { name: "Philippine Peso", symbol: "₱", value: "PHP" },
  { name: "Indonesian Rupiah", symbol: "Rp", value: "IDR" },
  { name: "Malaysian Ringgit", symbol: "RM", value: "MYR" },
  { name: "Hong Kong Dollar", symbol: "HK$", value: "HKD" },
  { name: "Hungarian Forint", symbol: "Ft", value: "HUF" },
  { name: "Czech Koruna", symbol: "Kč", value: "CZK" },
  { name: "Polish Zloty", symbol: "zł", value: "PLN" },
  { name: "Israeli Shekel", symbol: "₪", value: "ILS" },
  { name: "Chilean Peso", symbol: "CLP", value: "CLP" },
  { name: "Romanian Leu", symbol: "lei", value: "RON" },
  { name: "Danish Krone", symbol: "kr", value: "DKK" },
  { name: "Thai Baht", symbol: "฿", value: "THB" },
  { name: "UAE Dirham", symbol: "د.إ", value: "AED" },
  { name: "Colombian Peso", symbol: "COL$", value: "COP" },
  { name: "Saudi Riyal", symbol: "﷼", value: "SAR" },
  { name: "Malaysian Ringgit", symbol: "RM", value: "MYR" },
  { name: "Kuwaiti Dinar", symbol: "د.ك", value: "KWD" },
  { name: "Peruvian Nuevo Sol", symbol: "S/.", value: "PEN" },
  { name: "Vietnamese Dong", symbol: "₫", value: "VND" },
  { name: "Croatian Kuna", symbol: "kn", value: "HRK" },
  { name: "Costa Rican Colon", symbol: "₡", value: "CRC" },
  { name: "Argentine Peso", symbol: "AR$", value: "ARS" },
  { name: "Bulgarian Lev", symbol: "лв", value: "BGN" },
  { name: "Egyptian Pound", symbol: "E£", value: "EGP" },
  { name: "Qatari Rial", symbol: "﷼", value: "QAR" },
  { name: "Uruguayan Peso", symbol: "$U", value: "UYU" },
  { name: "New Taiwan Dollar", symbol: "NT$", value: "TWD" },
  { name: "Dominican Peso", symbol: "RD$", value: "DOP" },
  { name: "Moroccan Dirham", symbol: "د.م.", value: "MAD" },
  { name: "Omani Rial", symbol: "﷼", value: "OMR" },
];
